name: Splatoon3 Bot (daily twice)

on:
  schedule:
    - cron: '0 2,10 * * *'

permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      screenshot_types: salmon-run,gear-dailydrop,gear-regular
      message_types: salmon-run,gear-dailydrop,gear-regular
      artifact_name: salmon-run-and-gear
    secrets: inherit
