name: Splatoon3 Bot (every 2 hours)

on:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      profile: schedules
    secrets:
      UPYUN_BUCKET: ${{ secrets.UPYUN_BUCKET }}
      UPYUN_OPERATOR: ${{ secrets.UPYUN_OPERATOR }}
      UPYUN_SECRET: ${{ secrets.UPYUN_SECRET }}
      BOT_WECOM_CONFIG: ${{ secrets.BOT_WECOM_CONFIG }}
      BOT_DISCORD_CONFIG: ${{ secrets.BOT_DISCORD_CONFIG }}
      BOT_TELEGRAM_CONFIG: ${{ secrets.BOT_TELEGRAM_CONFIG }}
      BOT_QQ_CONFIG: ${{ secrets.BOT_QQ_CONFIG }}
      BOT_FEISHU_CONFIG: ${{ secrets.BOT_FEISHU_CONFIG }}
      BOT_DINGTALK_CONFIG: ${{ secrets.BOT_DINGTALK_CONFIG }}
