name: Splatoon3 Bot (every 2 hours)

on:
  schedule:
    - cron: '0 0,4,6,8,12,14,16,18,20,22 * * *'

permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      schedules: true
      salmon_run: false
      gear: false
    secrets:
      S3_CONFIG: ${{ secrets.S3_CONFIG }}
      BOT_WECOM_CONFIG: ${{ secrets.BOT_WECOM_CONFIG }}
      BOT_DISCORD_CONFIG: ${{ secrets.BOT_DISCORD_CONFIG }}
      BOT_TELEGRAM_CONFIG: ${{ secrets.BOT_TELEGRAM_CONFIG }}
      BOT_QQ_CONFIG: ${{ secrets.BOT_QQ_CONFIG }}
      BOT_FEISHU_CONFIG: ${{ secrets.BOT_FEISHU_CONFIG }}
      BOT_DINGTALK_CONFIG: ${{ secrets.BOT_DINGTALK_CONFIG }}
      BOT_WHATSAPP_CONFIG: ${{ secrets.BOT_WHATSAPP_CONFIG }}
      BOT_LINE_CONFIG: ${{ secrets.BOT_LINE_CONFIG }}
      BOT_SLACK_CONFIG: ${{ secrets.BOT_SLACK_CONFIG }}
