name: Splatoon3 Bot (manual)

on:
  workflow_dispatch:
    inputs:
      bot_message:
        description: Bot notification type
        default: schedules
        required: true
        type: choice
        options:
          - schedules
          - salmon-run
          - gear

permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      screenshot_types: ${{ inputs.bot_message == 'gear' && 'gear-dailydrop,gear-regular' || inputs.bot_message }}
      message_types: ${{ inputs.bot_message == 'gear' && 'gear-dailydrop,gear-regular' || inputs.bot_message }}
      artifact_name: ${{ inputs.bot_message }}
    secrets: inherit
