name: Splatoon3 Bot (every 2 hours)

on:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      screenshot_types: schedules
      message_types: schedules
      artifact_name: schedules
    secrets: inherit
