name: Splatoon3 Bot (manual)

on:
  workflow_dispatch:
    inputs:
      profile:
        description: Run Profile
        default: schedules
        required: true
        type: choice
        options:
          - schedules
          - salmon-run
          - gear
          - salmon-run-and-gear
permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      profile: ${{ inputs.profile }}
    secrets:
      UPYUN_BUCKET: ${{ secrets.UPYUN_BUCKET }}
      UPYUN_OPERATOR: ${{ secrets.UPYUN_OPERATOR }}
      UPYUN_SECRET: ${{ secrets.UPYUN_SECRET }}
      UPYUN_DOMAIN: ${{ secrets.UPYUN_DOMAIN }}
      BOT_WECOM_CONFIG: ${{ secrets.BOT_WECOM_CONFIG }}
      BOT_DISCORD_CONFIG: ${{ secrets.BOT_DISCORD_CONFIG }}
      BOT_TELEGRAM_CONFIG: ${{ secrets.BOT_TELEGRAM_CONFIG }}
      BOT_QQ_CONFIG: ${{ secrets.BOT_QQ_CONFIG }}
      BOT_FEISHU_CONFIG: ${{ secrets.BOT_FEISHU_CONFIG }}
      BOT_DINGTALK_CONFIG: ${{ secrets.BOT_DINGTALK_CONFIG }}
      BOT_WHATSAPP_CONFIG: ${{ secrets.BOT_WHATSAPP_CONFIG }}
      BOT_LINE_CONFIG: ${{ secrets.BOT_LINE_CONFIG }}
      BOT_SLACK_CONFIG: ${{ secrets.BOT_SLACK_CONFIG }}
