name: Splatooon3 Bot

on:
  # schedule:
  #   - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      bot_message:
        description: 'Bot notifications type'
        default: 'schedules'
        required: false
        type: choice
        options:
          - schedules
          - salmon-run
          - gear

jobs:
  generate_screenshots:
    name: Generate Screenshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          # run_install: |
          #   - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build FrontEnd Pages
        run: pnpm build

      - name: Download splatoon3.ink Data
        run: ./scripts/download_data.sh

      - name: Generate Screenshots
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          CI: 'true'
        with:
          args: npm run start:${{ inputs.bot_message }} # run command inside image

      - run: ls screenshots

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png
          retention-days: 3

  trigger_bot_webhooks:
    if: inputs.bot_message == 'schedules'
    needs: generate_screenshots
    strategy:
      matrix:
        screenshot_name: [regular, anarchy-open, anarchy-series]
    name: Trigger Bot Webhook (${{ matrix.screenshot_name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Screenshot
        uses: actions/download-artifact@v3
        with:
          name: screenshots
          path: screenshots/

      - run: ls screenshots

      - name: Trigger Bot Webhook (${{ inputs.bot_message }})
        env:
          BOT_WEBHOOK_URL: ${{ secrets.SPLATOON_SCHEDULES_REGULAR_BOT_URL }}
          SCREENSHOT_FILENAME: screenshots/${{ matrix.screenshot_name }}.png
        # run: ./scripts/trigger_bot_webhook.sh
        run: node ./scripts/trigger_bot_webhook.js
