name: Test timezone

on:
  workflow_dispatch:

permissions: {}

jobs:
  test-timezone:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Print current time
        run: date '+%Y-%m-%d %H:%M:%S %Z'
